// v.1.1.8 =========================================================
// lib/actions.ts
'use server';

import { PrismaClient } from '@prisma/client';
import { revalidatePath } from 'next/cache';
import { put } from '@vercel/blob';

const prisma = new PrismaClient();

export interface Contact {
  id: number;
  uid?: string | null;
  first_name: string;
  last_name?: string | null;
  phone_number?: string | null;
  email?: string | null;
  company?: string | null;
  job_title?: string | null;
  notes?: string | null;
  profile_image_url?: string | null;
  created_at?: Date | null;
  updated_at?: Date | null;
}

const getNullIfEmpty = (value: FormDataEntryValue | null): string | null => {
  if (value === '' || value === null) {
    return null;
  }
  return String(value);
};

async function uploadImage(file: File): Promise<string | null> {
  if (!file || file.size === 0) {
    return null;
  }
  try {
    const filename = `${Date.now()}-${file.name}`;
    const { url } = await put(filename, file, { access: 'public' });
    return url;
  } catch (error) {
    console.error('Failed to upload image to Vercel Blob:', error);
    return null;
  }
}

export async function createContact(formData: FormData) {
  await new Promise(res => setTimeout(res, 1500));

  const first_name = formData.get('first_name') as string;
  const last_name = getNullIfEmpty(formData.get('last_name'));
  const phone_number = getNullIfEmpty(formData.get('phone_number'));
  const email = getNullIfEmpty(formData.get('email'));
  const company = getNullIfEmpty(formData.get('company'));
  const job_title = getNullIfEmpty(formData.get('job_title'));
  const notes = getNullIfEmpty(formData.get('notes'));
  const imageFile = formData.get('profile_image') as File | null;

  if (!first_name) {
    return { error: 'First name is required.' };
  }

  let profile_image_url: string | null = null;
  if (imageFile && imageFile.size > 0) {
    profile_image_url = await uploadImage(imageFile);
  }

  try {
    await prisma.contacts.create({
      data: {
        // UID is now generated by the database automatically.
        first_name: first_name,
        last_name: last_name,
        phone_number: phone_number,
        email: email,
        company: company,
        job_title: job_title,
        notes: notes,
        profile_image_url: profile_image_url,
      },
    });
    revalidatePath('/');
    return { success: true };
  } catch (error) {
    let errorMessage = 'An unknown error occurred.';
    if (error instanceof Error) {
        console.error(`[DB Create Error] ${error.message}`, error.stack);
        errorMessage = error.message;
    } else {
        console.error('[DB Create Error] An unknown error occurred:', error);
    }
    return { error: `Database Error: ${errorMessage}` };
  }
}

export async function updateContact(id: number, formData: FormData) {
  await new Promise(res => setTimeout(res, 1500));

  const first_name = formData.get('first_name') as string;
  const last_name = getNullIfEmpty(formData.get('last_name'));
  const phone_number = getNullIfEmpty(formData.get('phone_number'));
  const email = getNullIfEmpty(formData.get('email'));
  const company = getNullIfEmpty(formData.get('company'));
  const job_title = getNullIfEmpty(formData.get('job_title'));
  const notes = getNullIfEmpty(formData.get('notes'));
  const imageFile = formData.get('profile_image') as File | null;
  const currentImageUrl = formData.get('current_image_url') as string | null;
  const deleteImage = formData.get('delete_image') === 'on';

  if (!first_name) {
    return { error: 'First name is required.' };
  }

  let new_profile_image_url: string | null = currentImageUrl;

  if (deleteImage) {
      new_profile_image_url = null;
  } else if (imageFile && imageFile.size > 0) {
      new_profile_image_url = await uploadImage(imageFile);
  }

  try {
    await prisma.contacts.update({
      where: { id: id },
      data: {
        first_name: first_name,
        last_name: last_name,
        phone_number: phone_number,
        email: email,
        company: company,
        job_title: job_title,
        notes: notes,
        profile_image_url: new_profile_image_url,
      },
    });
    revalidatePath('/');
    return { success: true };
  } catch (error) {
    let errorMessage = 'An unknown error occurred.';
    if (error instanceof Error) {
        console.error(`[DB Update Error] ${error.message}`, error.stack);
        errorMessage = error.message;
    } else {
        console.error('[DB Update Error] An unknown error occurred:', error);
    }
    return { error: `Database Error: ${errorMessage}` };
  }
}

export async function deleteContact(id: number) {
  try {
    await prisma.contacts.delete({
      where: { id: id },
    });
    revalidatePath('/');
    return { success: true };
  } catch (error) {
    console.error(`Failed to delete contact with ID ${id}:`, error);
    return { error: `Failed to delete contact with ID ${id}.` };
  }
}

export async function getContacts(): Promise<Contact[]> {
  try {
    const contacts = await prisma.contacts.findMany({
      orderBy: { created_at: 'desc' },
    });
    return contacts;
  } catch (error) {
    console.error('Failed to fetch contacts:', error);
    return [];
  }
}

export async function getContactById(id: number): Promise<Contact | null> {
  try {
    const contact = await prisma.contacts.findUnique({
      where: { id: id },
    });
    return contact;
  } catch (error) {
    console.error(`Failed to fetch contact with ID ${id}:`, error);
    return null;
  }
}

export async function testDbConnection() {
  try {
    await prisma.$queryRaw`SELECT 1`; 
    console.log('Database connection successful!');
    return { success: true, message: 'Database connection successful!' };
  } catch (error: unknown) {
    console.error('Database connection failed:', error);
    let errorMessage: string;
    
    if (error instanceof Error) {
      errorMessage = error.message;
    } else {
      errorMessage = String(error);
    }

    return { 
      success: false, 
      message: `Database connection failed: ${errorMessage}` 
    };
  }
}